/**
 * The card, rendered from a payload the SERVER produced.
 *
 * Every other fixture in this suite is hand-written, which is how the card
 * once rendered every conflict as an empty string while this suite was
 * entirely green: the fixtures used a `device` key the backend had stopped
 * sending, so they agreed with each other and with nothing else.
 *
 * `fixtures/state-payload.json` is generated by
 * `tests/test_frontend_fixture.py` from a real `shabbat_scheduler/rules/list`
 * round trip, and that Python test FAILS if the committed copy drifts from
 * what the server sends. Regenerate with:
 *
 *   REGEN_FRONTEND_FIXTURE=1 uv run pytest tests/test_frontend_fixture.py
 *
 * Nothing in this file may hand-write a payload field. If an assertion here
 * needs a value the fixture does not carry, change the generator.
 */
import { describe, expect, it } from 'vitest';
import '../src/card';
import type { CardState, DayGroup, RuleData, WarningData } from '../src/types';
import { dayGroups, renderCardWithState, ruleRows, type Card } from './helpers';
import payload from './fixtures/state-payload.json';

const state = payload as unknown as CardState;

/** The conflict on rules the card is actually drawing. */
const onDisplayedRules = (): WarningData =>
  state.warnings.find((warning) => warning.profile === state.block!.length)!;

/** The conflict in a profile the card is not drawing at all. */
const onHiddenProfile = (): WarningData =>
  state.warnings.find((warning) => warning.profile !== state.block!.length)!;

const displayedRules = (): RuleData[] =>
  state.rules.filter((rule) => rule.profile === state.block!.length);

const text = (el: Card): string => el.shadowRoot!.textContent!.trim();

describe('the card, against a real server payload', () => {
  it('carries the two conflicts the generator promises', () => {
    // Not a card assertion - a guard on the fixture, so that a generator
    // change which quietly drops a conflict fails here loudly instead of
    // turning the rendering assertions below into vacuous ones.
    expect(state.warnings.length).toBe(2);
    expect(onDisplayedRules()).toBeDefined();
    expect(onHiddenProfile()).toBeDefined();
    for (const warning of state.warnings) {
      expect(warning.kind).toBe('conflict');
      expect(warning.targets!.length).toBeGreaterThan(0);
      // `toStrictEqual`/`in` rather than any `toEqual` shape check: Vitest
      // treats an omitted key as equal to `key: undefined`, so a `toEqual`
      // here would pass on a payload that really did carry v1's `device`.
      expect('device' in warning).toBe(false);
    }
  });

  it('renders a conflict on displayed rules as visible text on their rows', async () => {
    const el = await renderCardWithState(state);
    const warning = onDisplayedRules();
    const rows = await ruleRows(el);
    const conflicted = rows.filter((row) =>
      warning.rule_ids!.includes((row.rule as RuleData).id),
    );

    expect(conflicted.length).toBe(warning.rule_ids!.length);
    for (const row of conflicted) {
      const detail = row.shadowRoot!.querySelector('.conflict-detail');
      expect(detail).not.toBeNull();
      // The bug was an EMPTY string where an entity id belonged, so the
      // entity ids the server actually sent have to appear.
      const shown = detail!.textContent!.trim();
      expect(shown.length).toBeGreaterThan(0);
      for (const target of warning.targets!) expect(shown).toContain(target);
      expect(shown).toContain(warning.time!);
    }
  });

  it('renders a conflict on a hidden profile as visible text in the banner', async () => {
    const el = await renderCardWithState(state);
    const warning = onHiddenProfile();
    const warnings = el.shadowRoot!.querySelector('shabbat-warnings') as Card;
    expect(warnings).not.toBeNull();
    await warnings.updateComplete;

    expect(warnings.shadowRoot!.querySelector('.banner')).not.toBeNull();
    const shown = text(warnings);
    expect(shown.length).toBeGreaterThan(0);
    for (const target of warning.targets!) expect(shown).toContain(target);
  });

  it('does not repeat a displayed conflict in the banner', async () => {
    // The other half of the split above: a conflict shown on a row must
    // not also be shown in the banner, or every conflict reads as two.
    const el = await renderCardWithState(state);
    const warnings = el.shadowRoot!.querySelector('shabbat-warnings') as Card;
    await warnings.updateComplete;
    const shown = text(warnings);
    for (const ruleId of onDisplayedRules().rule_ids!) {
      expect(shown).not.toContain(ruleId);
    }
    expect(shown.split(onHiddenProfile().time!).length - 1).toBe(1);
  });

  it('renders a row for every rule in the block the payload describes', async () => {
    const el = await renderCardWithState(state);
    const rows = await ruleRows(el);
    // Not `state.rules.length`: the payload carries every profile's rules
    // and the card draws only the coming block's, on purpose (a 3-day
    // Chag's rules must not appear on a plain Shabbat).
    expect(rows.length).toBe(displayedRules().length);
    expect(rows.length).toBeGreaterThan(0);
    expect(rows.map((row) => (row.rule as RuleData).id).sort()).toEqual(
      displayedRules().map((rule) => rule.id).sort(),
    );
  });

  it('renders each row with a non-empty time and a description of its action', async () => {
    const el = await renderCardWithState(state);
    for (const row of await ruleRows(el)) {
      const rule = row.rule as RuleData;
      expect(text(row).length).toBeGreaterThan(0);
      expect(row.shadowRoot!.querySelector('.time')!.textContent).toBe(
        rule.time.slice(0, 5),
      );
      const brief = row.shadowRoot!.querySelector('.brief')!.textContent!;
      expect(brief).toContain(rule.action);
      // A rule naming no target of its own falls back to the defaults, so
      // no row may describe itself as applying to nothing.
      expect(brief.length).toBeGreaterThan(rule.action.length);
    }
  });

  it('reads the master switch entity id the server resolved, not a guess', async () => {
    // Every hand-written fixture in this suite invents 'switch.master'.
    // The real one is slugified from a user-editable name, which is why
    // the server resolves it and the card must not construct it.
    const el = await renderCardWithState(state);
    const header = el.shadowRoot!.querySelector('shabbat-block-header') as Card;
    await header.updateComplete;
    expect(state.master_entity_id).not.toBe('switch.master');
    expect(header.masterEntityId).toBe(state.master_entity_id);
    expect(header.enabled).toBe(state.enabled);
    expect(header.dryRun).toBe(state.dry_run);
  });

  it('draws the block dates the server sent, on the right days', async () => {
    // Dates come from `block.dates`, an object keyed 'erev' | '1' | ... .
    // A card reading it positionally renders the block backwards, and the
    // server is the only thing that knows the real dates.
    const el = await renderCardWithState(state);
    const groups = await dayGroups(el);
    expect(groups.length).toBe(Object.keys(state.block!.dates).length);
    for (const group of groups) {
      const day = (group.group as DayGroup).day;
      expect(group.shadowRoot!.querySelector('.date')!.textContent).toBe(
        state.block!.dates[day],
      );
    }
    const expected = ['erev'];
    for (let day = 1; day <= state.block!.length; day += 1) {
      expected.push(String(day));
    }
    expect(groups.map((group) => (group.group as DayGroup).day)).toEqual(expected);
  });
});
