/**
 * The card, rendered from a payload the SERVER produced.
 *
 * Every other fixture in this suite is hand-written, which is how the card
 * once rendered every conflict as an empty string while this suite was
 * entirely green: the fixtures used a `device` key the backend had stopped
 * sending, so they agreed with each other and with nothing else.
 *
 * `fixtures/state-payload.json` is generated by
 * `tests/test_frontend_fixture.py` from a real `shabbat_scheduler/rules/list`
 * round trip, and that Python test FAILS if the committed copy drifts from
 * what the server sends. Regenerate with:
 *
 *   REGEN_FRONTEND_FIXTURE=1 uv run pytest tests/test_frontend_fixture.py
 *
 * Nothing in this file may hand-write a payload field. If an assertion here
 * needs a value the fixture does not carry, change the generator.
 */
import { describe, expect, it } from 'vitest';
import '../src/card';
import type { CardState, DayGroup, RuleData, WarningData } from '../src/types';
import { dayGroups, renderCardWithState, ruleRows, type Card } from './helpers';
import payload from './fixtures/state-payload.json';

/**
 * Assigned to `CardState` with NO cast, deliberately.
 *
 * That makes `npm run typecheck` a second drift guard, free and cheaper
 * than the Python one: if `_state_payload` ever sends a shape `types.ts`
 * does not describe, this line stops compiling. A `payload as unknown as
 * CardState` would have thrown exactly that away - it asserts the very
 * thing the file exists to verify.
 */
const state: CardState = payload;

/** The conflict on rules the card is actually drawing. */
const onDisplayedRules = (): WarningData =>
  state.warnings.find((warning) => warning.profile === state.block!.length)!;

/** The conflict in a profile the card is not drawing at all. */
const onHiddenProfile = (): WarningData =>
  state.warnings.find((warning) => warning.profile !== state.block!.length)!;

/** The days the card draws for this block: 'erev', then 1..length. */
const blockDays = (): string[] => {
  const days = ['erev'];
  for (let day = 1; day <= state.block!.length; day += 1) days.push(String(day));
  return days;
};

/**
 * The rules `buildGroups` would actually draw - BOTH halves of its filter.
 * Profile alone is not it: a rule whose profile matches but whose `day` is
 * outside the block (a day-2 rule in a 1-day block) is not drawn either,
 * and counting it would make this test assert a bug.
 */
const displayedRules = (): RuleData[] =>
  state.rules.filter(
    (rule) =>
      rule.profile === state.block!.length && blockDays().includes(rule.day),
  );

/**
 * The displayed rule the SERVER recorded an outcome for.
 *
 * The generator runs dry with a frozen clock, so `erev-salon` really is
 * replayed and really is refused as too stale - see the `_FROZEN_NOW` note
 * in `tests/test_frontend_fixture.py`. Nothing here may hand-write that
 * outcome; it is read back out of the committed payload.
 */
const withOutcome = (): RuleData =>
  displayedRules().find((rule) => rule.last_outcome !== null)!;

const text = (el: Card): string => el.shadowRoot!.textContent!.trim();

/** How many times `needle` appears in `haystack`. */
const occurrences = (haystack: string, needle: string): number =>
  haystack.split(needle).length - 1;

describe('the card, against a real server payload', () => {
  it('carries the two conflicts the generator promises', () => {
    // Not a card assertion - a guard on the fixture, so that a generator
    // change which quietly drops a conflict fails here loudly instead of
    // turning the rendering assertions below into vacuous ones.
    expect(state.warnings.length).toBe(2);
    expect(onDisplayedRules()).toBeDefined();
    expect(onHiddenProfile()).toBeDefined();
    for (const warning of state.warnings) {
      expect(warning.kind).toBe('conflict');
      expect(warning.targets!.length).toBeGreaterThan(0);
      // `toStrictEqual`/`in` rather than any `toEqual` shape check: Vitest
      // treats an omitted key as equal to `key: undefined`, so a `toEqual`
      // here would pass on a payload that really did carry v1's `device`.
      expect('device' in warning).toBe(false);
    }
  });

  it('renders a conflict on displayed rules as visible text on their rows', async () => {
    const el = await renderCardWithState(state);
    const warning = onDisplayedRules();
    const rows = await ruleRows(el);
    const conflicted = rows.filter((row) =>
      warning.rule_ids!.includes((row.rule as RuleData).id),
    );

    expect(conflicted.length).toBe(warning.rule_ids!.length);
    for (const row of conflicted) {
      const detail = row.shadowRoot!.querySelector('.conflict-detail');
      expect(detail).not.toBeNull();
      // The bug was an EMPTY string where an entity id belonged, so the
      // entity ids the server actually sent have to appear.
      const shown = detail!.textContent!.trim();
      expect(shown.length).toBeGreaterThan(0);
      for (const target of warning.targets!) expect(shown).toContain(target);
      expect(shown).toContain(warning.time!);
    }
  });

  it('renders a conflict on a hidden profile as visible text in the banner', async () => {
    const el = await renderCardWithState(state);
    const warning = onHiddenProfile();
    const warnings = el.shadowRoot!.querySelector('shabbat-warnings') as Card;
    expect(warnings).not.toBeNull();
    await warnings.updateComplete;

    expect(warnings.shadowRoot!.querySelector('.banner')).not.toBeNull();
    const shown = text(warnings);
    expect(shown.length).toBeGreaterThan(0);
    for (const target of warning.targets!) expect(shown).toContain(target);
  });

  it('does not repeat a displayed conflict in the banner', async () => {
    // The other half of the split above: a conflict shown on a row must not
    // also be shown in the banner, or every conflict reads as two.
    //
    // The discriminator has to be the conflict's TIME. Rule ids are not:
    // `formatWarning` never emits an id, so asserting the banner omits
    // them is vacuous - it passes with `displayedRuleIds` deleted
    // entirely, which is the exact bug this test is named for. Targets are
    // not either: both conflicts in this payload resolve to
    // `climate.mamad`, so the two are indistinguishable by target. The
    // times differ, and they are what `formatWarning` actually renders.
    const el = await renderCardWithState(state);
    const warnings = el.shadowRoot!.querySelector('shabbat-warnings') as Card;
    await warnings.updateComplete;
    const banner = text(warnings);

    expect(occurrences(banner, onDisplayedRules().time!)).toBe(0);
    // Paired with the line above so it cannot pass for the wrong reason: an
    // empty banner would satisfy the zero, and a banner rendering the
    // hidden conflict twice would be its own bug.
    expect(occurrences(banner, onHiddenProfile().time!)).toBe(1);
  });

  it('renders a row for every rule in the block the payload describes', async () => {
    const el = await renderCardWithState(state);
    const rows = await ruleRows(el);
    // Not `state.rules.length`: the payload carries every profile's rules
    // and the card draws only the coming block's, on purpose (a 3-day
    // Chag's rules must not appear on a plain Shabbat).
    expect(rows.length).toBe(displayedRules().length);
    expect(rows.length).toBeGreaterThan(0);
    expect(rows.map((row) => (row.rule as RuleData).id).sort()).toEqual(
      displayedRules().map((rule) => rule.id).sort(),
    );
  });

  it('renders each row with a non-empty time and a description of its action', async () => {
    const el = await renderCardWithState(state);
    for (const row of await ruleRows(el)) {
      const rule = row.rule as RuleData;
      expect(text(row).length).toBeGreaterThan(0);
      expect(row.shadowRoot!.querySelector('.time')!.textContent).toBe(
        rule.time.slice(0, 5),
      );
      const brief = row.shadowRoot!.querySelector('.brief')!.textContent!;
      expect(brief).toContain(rule.action);
      // A rule naming no target of its own falls back to the defaults, so
      // no row may describe itself as applying to nothing.
      expect(brief.length).toBeGreaterThan(rule.action.length);
    }
  });

  it('describes each row with the rule data merged over the defaults', async () => {
    // `ruleBrief` merges `defaults.data` UNDER the rule's own, and the
    // generated payload seeds that where merge and replace visibly differ:
    // one rule overrides a defaults key with a different value, another adds
    // a key the defaults do not carry at all. A payload where every rule's
    // `data` was empty would render identically under either behaviour.
    const el = await renderCardWithState(state);
    const defaultData = state.defaults.data ?? {};
    let overrides = 0;

    for (const row of await ruleRows(el)) {
      const rule = row.rule as RuleData;
      const brief = row.shadowRoot!.querySelector('.brief')!.textContent!;
      for (const [key, value] of Object.entries({ ...defaultData, ...rule.data })) {
        expect(brief).toContain(String(value));
        if (key in rule.data && key in defaultData && rule.data[key] !== defaultData[key]) {
          // The overridden default must be GONE, not merely outnumbered.
          expect(brief).not.toContain(String(defaultData[key]));
          overrides += 1;
        }
      }
    }

    expect(overrides).toBeGreaterThan(0);
  });

  it('reads the master switch entity id the server resolved, not a guess', async () => {
    // Every hand-written fixture in this suite invents 'switch.master'.
    // The real one is slugified from a user-editable name, which is why
    // the server resolves it and the card must not construct it.
    const el = await renderCardWithState(state);
    const header = el.shadowRoot!.querySelector('shabbat-block-header') as Card;
    await header.updateComplete;
    expect(state.master_entity_id).not.toBe('switch.master');
    expect(header.masterEntityId).toBe(state.master_entity_id);
    expect(header.enabled).toBe(state.enabled);
    expect(header.dryRun).toBe(state.dry_run);
  });

  it('carries one recorded outcome and one rule that never ran', () => {
    // A guard on the fixture, like the conflict guard above: both halves
    // have to be real, or the two rendering assertions below go vacuous in
    // opposite directions. If the generator ever stops recording, or
    // records for everything, this fails loudly instead.
    const rule = withOutcome();
    expect(rule).toBeDefined();
    expect(rule.last_outcome!.outcome.length).toBeGreaterThan(0);
    expect(rule.last_outcome!.detail).toBeTruthy();
    expect(displayedRules().some((other) => other.last_outcome === null)).toBe(true);
  });

  /**
   * The half of Gap A that Task 11 left open.
   *
   * The generated payload now carries a real `last_outcome`, but until this
   * test nothing on the frontend side read it: a card that stopped
   * rendering the field entirely would have been caught only by
   * `rule-row.test.ts`, whose fixture is HAND-WRITTEN - which is exactly
   * the pattern that let the card render every conflict as an empty string
   * through 168 green tests.
   *
   * "A rule that does not fire must say why - in the logbook AND on the
   * card." The server's own words have to be visible text on the row, not
   * merely a property that arrived.
   */
  it("renders the server's recorded outcome as visible text on its own row", async () => {
    const el = await renderCardWithState(state);
    const rule = withOutcome();
    const row = (await ruleRows(el)).find(
      (candidate) => (candidate.rule as RuleData).id === rule.id,
    )!;
    expect(row).toBeDefined();

    const line = row.shadowRoot!.querySelector('.last-outcome');
    expect(line).not.toBeNull();
    const shown = line!.textContent!.trim();
    expect(shown.length).toBeGreaterThan(0);
    // The server's own wording, verbatim - the same string the logbook row
    // carries. An empty or "undefined" line is the bug this file exists for.
    expect(shown).toContain(rule.last_outcome!.detail!);
    expect(shown).not.toContain('undefined');
    // And a verdict as well as the reason: a row showing only the raw
    // detail never says whether the rule ran. Same idiom as the `.brief`
    // assertion above.
    expect(shown.length).toBeGreaterThan(rule.last_outcome!.detail!.length);
    // This rule did NOT run, so it must not be drawn as quietly as one
    // that did.
    expect([...line!.classList]).toContain('bad');
  });

  it('renders no outcome line at all for a rule the server says never ran', async () => {
    const el = await renderCardWithState(state);
    const never = displayedRules().find((rule) => rule.last_outcome === null)!;
    const row = (await ruleRows(el)).find(
      (candidate) => (candidate.rule as RuleData).id === never.id,
    )!;
    expect(row.shadowRoot!.querySelector('.last-outcome')).toBeNull();
  });

  it('draws the block dates the server sent, on the right days', async () => {
    // Dates come from `block.dates`, an object keyed 'erev' | '1' | ... .
    // A card reading it positionally renders the block backwards, and the
    // server is the only thing that knows the real dates.
    const el = await renderCardWithState(state);
    const groups = await dayGroups(el);
    expect(groups.length).toBe(Object.keys(state.block!.dates).length);
    for (const group of groups) {
      const day = (group.group as DayGroup).day;
      expect(group.shadowRoot!.querySelector('.date')!.textContent).toBe(
        state.block!.dates[day],
      );
    }
    expect(groups.map((group) => (group.group as DayGroup).day)).toEqual(blockDays());
  });
});
