/** Mirrors the integration's own en/he translations. */

const STRINGS = {
  en: {
    erev: 'Erev',
    day: 'Day',
    candle_lighting: 'Candle lighting',
    havdalah: 'Havdalah',
    master: 'Shabbat Scheduler',
    dry_run: 'Dry run',
    no_block: 'No upcoming Shabbat could be derived from the Jewish Calendar sensors.',
    not_set_up: 'Shabbat Scheduler is not configured.',
    stale: 'Connection lost — showing the last known state.',
    // Deliberately distinct from `stale`. The server was reachable and
    // refused the call - saying "connection lost" there is a wrong
    // diagnosis that sends someone to check the network.
    command_failed: 'That did not go through. Nothing was changed.',
    no_rules: 'No rules for this block.',
    disabled_rule: 'disabled',
    conflict_prefix: 'Conflict',
    edit_rule: 'Edit rule',
    add_rule: 'Add rule',
    time: 'Time',
    action: 'Action',
    name: 'Name',
    enabled: 'Enabled',
    advanced: 'Advanced',
    icon: 'Icon',
    colour: 'Colour',
    save: 'Save',
    cancel: 'Cancel',
    delete_rule: 'Delete',
    duplicate: 'Duplicate',
    read_only: 'You do not have permission to change the schedule.',
    will_conflict: 'This overlaps another rule. You can still save it — nothing is resolved for you.',
    defaults_title: 'Shared defaults',
    defaults_help: 'Rules inherit these unless they set their own.',
    inherits_target: 'No target set — inherits from the shared defaults:',
    // The read-only half of the rule dialog. Saying "not editable here"
    // out loud is the point: a field the card silently omitted would read
    // as a field the rule does not have.
    read_only_fields: 'Not editable here yet — shown so you can see what this rule actually carries. Use the YAML import/export service to change them.',
    target: 'Target',
    data: 'Data',
    condition: 'Conditions',
    replay: 'Re-apply after a restart',
    replay_no: 'no',
    replay_yes: 'yes',
    replay_within: 'within',
    none_set: 'none',
    migration_error: 'This rule could not be converted from the old format and will not fire:',
    preview_banner: 'Preview — not the coming Shabbat. Dates are not shown because this block is not scheduled.',
    inherits_target_from_defaults: 'Inherited from the shared defaults:',
    target_none: 'No target — this rule will not reach anything.',
    replay_after_restart: 'Replay after a restart',
    replay_within_label: 'Only if less than',
    replay_help: 'Off by default: after a restart, nothing that already passed is re-run.',
    conditions: 'Conditions',
    conditions_help: 'All conditions must pass, or the rule does not run and says why.',
    add_condition: 'Add condition',
    remove_condition: 'Remove',
    condition_unparseable: 'Not valid YAML — this condition is not being saved.',
    condition_not_a_mapping: 'A condition must be a mapping, like `condition: state`.',
  },
  he: {
    erev: 'ערב',
    day: 'יום',
    candle_lighting: 'הדלקת נרות',
    havdalah: 'הבדלה',
    master: 'שעון שבת',
    dry_run: 'הרצה יבשה',
    no_block: 'לא ניתן לגזור שבת קרובה מחיישני לוח השנה העברי.',
    not_set_up: 'שעון שבת אינו מוגדר.',
    stale: 'החיבור אבד — מוצג המצב האחרון הידוע.',
    command_failed: 'הפעולה לא בוצעה. שום דבר לא השתנה.',
    no_rules: 'אין כללים לבלוק הזה.',
    disabled_rule: 'מושבת',
    conflict_prefix: 'התנגשות',
    edit_rule: 'עריכת כלל',
    add_rule: 'הוספת כלל',
    time: 'שעה',
    action: 'פעולה',
    name: 'שם',
    enabled: 'מופעל',
    advanced: 'מתקדם',
    icon: 'סמל',
    colour: 'צבע',
    save: 'שמירה',
    cancel: 'ביטול',
    delete_rule: 'מחיקה',
    duplicate: 'שכפול',
    read_only: 'אין לך הרשאה לשנות את הלוח.',
    will_conflict: 'הכלל חופף לכלל אחר. אפשר לשמור בכל זאת — שום דבר לא ייפתר עבורך.',
    defaults_title: 'ברירות מחדל משותפות',
    defaults_help: 'כללים יורשים אותן אלא אם הגדירו משלהם.',
    inherits_target: 'לא נבחר יעד — יורש מברירות המחדל המשותפות:',
    read_only_fields: 'לא ניתן לערוך כאן עדיין — מוצג כדי שתראו מה הכלל באמת מכיל. לשינוי השתמשו בשירות ייבוא/ייצוא YAML.',
    target: 'יעד',
    data: 'נתונים',
    condition: 'תנאים',
    replay: 'החלה מחדש לאחר הפעלה מחדש',
    replay_no: 'לא',
    replay_yes: 'כן',
    replay_within: 'בתוך',
    none_set: 'ללא',
    migration_error: 'לא ניתן להמיר את הכלל הזה מהפורמט הישן והוא לא יופעל:',
    preview_banner: 'תצוגה מקדימה — לא השבת הקרובה. התאריכים אינם מוצגים כי הבלוק הזה אינו מתוכנן.',
    inherits_target_from_defaults: 'נורש מברירת המחדל המשותפת:',
    target_none: 'ללא יעד — הכלל לא יפעל על שום דבר.',
    replay_after_restart: 'הפעלה חוזרת לאחר אתחול',
    replay_within_label: 'רק אם עברו פחות מ־',
    replay_help: 'כברירת מחדל כבוי: לאחר אתחול, מה שכבר עבר לא יופעל שוב.',
    conditions: 'תנאים',
    conditions_help: 'כל התנאים חייבים להתקיים, אחרת הכלל לא ירוץ ויציין זאת.',
    add_condition: 'הוספת תנאי',
    remove_condition: 'הסרה',
    condition_unparseable: 'YAML לא תקין — התנאי הזה לא נשמר.',
    condition_not_a_mapping: 'תנאי חייב להיות מפה, כמו `condition: state`.',
  },
} as const;

export type StringKey = keyof (typeof STRINGS)['en'];

export function t(language: string | undefined, key: StringKey): string {
  const table = language === 'he' ? STRINGS.he : STRINGS.en;
  return table[key];
}
