/** Mirrors the integration's own en/he translations. */

const STRINGS = {
  en: {
    erev: 'Erev',
    day: 'Day',
    candle_lighting: 'Candle lighting',
    havdalah: 'Havdalah',
    master: 'Shabbat Scheduler',
    no_block: 'No upcoming Shabbat could be derived from the Jewish Calendar sensors.',
    not_set_up: 'Shabbat Scheduler is not configured.',
    stale: 'Connection lost — showing the last known state.',
    // Deliberately distinct from `stale`. The server was reachable and
    // refused the call - saying "connection lost" there is a wrong
    // diagnosis that sends someone to check the network.
    command_failed: 'That did not go through. Nothing was changed.',
    no_rules: 'No rules for this block.',
    disabled_rule: 'disabled',
    conflict_prefix: 'Conflict',
    edit_rule: 'Edit rule',
    add_rule: 'Add rule',
    time: 'Time',
    name: 'Name',
    enabled: 'Enabled',
    advanced: 'Advanced',
    icon: 'Icon',
    colour: 'Colour',
    save: 'Save',
    cancel: 'Cancel',
    delete_rule: 'Delete',
    duplicate: 'Duplicate',
    read_only: 'You do not have permission to change the schedule.',
    will_conflict: 'This overlaps another rule. You can still save it — nothing is resolved for you.',
    defaults_title: 'Shared defaults',
    defaults_help: 'Rules inherit these unless they set their own.',
    target: 'Target',
    data: 'Data',
    migration_error: 'This rule could not be converted from the old format and will not fire:',
    preview_banner: 'Preview — not the coming Shabbat. Dates are not shown because this block is not scheduled.',
    inherits_target_from_defaults: 'Inherited from the shared defaults:',
    target_none: 'No target — this rule will not reach anything.',
    replay_after_restart: 'Replay after a restart',
    replay_within_label: 'Only if less than',
    replay_help: 'Off by default: after a restart, nothing that already passed is re-run.',
    conditions: 'Conditions',
    conditions_help: 'All conditions must pass, or the rule does not run and says why.',
    add_condition: 'Add condition',
    remove_condition: 'Remove',
    condition_unparseable: 'Not valid YAML — this condition is not being saved.',
    condition_not_a_mapping: 'A condition must be a mapping, like `condition: state`.',
    // What happened the last time a rule came due. The wording deliberately
    // mirrors logbook.py's rows: the person reading the card and the person
    // reading the logbook must not be told two different things about the
    // same rule. "Did not run" appears in each of the four non-firing
    // outcomes and in neither of the two firing ones.
    outcome_called: 'Fired',
    outcome_would_call: 'Would have fired [dry run]',
    outcome_failed: 'Did not run — failed',
    outcome_blocked: 'Did not run — blocked',
    outcome_skipped_stale: 'Did not run — skipped as stale',
    // The default path, and the reason this string exists: replay is off
    // unless the rule's author switched it on, so this is what a whole
    // schedule reads after an ordinary restart. The server sends its own
    // `detail` alongside it ("replay is switched off for this rule"), the
    // same words the logbook row carries.
    outcome_skipped_no_replay: 'Did not run — was due after a restart, replay is off',
    // A verdict from a server one version ahead of this card. Saying this
    // beats rendering an empty line that looks like nothing happened.
    outcome_unknown: 'Finished with no reported outcome',
    // The English values here must stay byte-identical to
    // UNKNOWN_ENTITY_PREFIX and NO_LIVE_TARGETS_NOTE in const.py - see
    // `formatOutcome`, which de-duplicates against the server's own English
    // wording already present in `detail`.
    outcome_no_such_entity: 'no such entity: ',
    outcome_reached_nothing: 'reached no entity that exists',
    run_now_button: 'Run now',
    run_now_simulate: 'Simulate',
    run_now_real: 'Run for real',
    run_now_disabled_dirty: 'Save your changes first',
    simulate_title: 'Test your schedule',
    simulate_profile: 'Block length',
    simulate_day: 'Day',
    simulate_force_conditions: 'Force conditions to pass',
    simulate_this_day: 'Simulate this day',
    simulate_run_for_real: 'Run this day for real',
    simulate_run_for_real_confirm: 'This will actually operate your devices, in order, for',
    clone_day_prefix: 'Clone day',
    clone_profile_prefix: 'Clone the',
    clone_profile_suffix: '-day profile',
    clone_target_profile: 'Target block length',
    clone_target_day: 'Target day',
    clone_extend: 'Extend',
    clone_overwrite: 'Overwrite',
    clone_target_has_rules: 'The target has existing rule(s):',
    clone_confirm: 'Clone',
    clone_landed: 'Cloned',
    clone_failed: 'Not cloned',
    clone_none: 'none',
  },
  he: {
    erev: 'ערב',
    day: 'יום',
    candle_lighting: 'הדלקת נרות',
    havdalah: 'הבדלה',
    master: 'שעון שבת',
    no_block: 'לא ניתן לגזור שבת קרובה מחיישני לוח השנה העברי.',
    not_set_up: 'שעון שבת אינו מוגדר.',
    stale: 'החיבור אבד — מוצג המצב האחרון הידוע.',
    command_failed: 'הפעולה לא בוצעה. שום דבר לא השתנה.',
    no_rules: 'אין כללים לבלוק הזה.',
    disabled_rule: 'מושבת',
    conflict_prefix: 'התנגשות',
    edit_rule: 'עריכת כלל',
    add_rule: 'הוספת כלל',
    time: 'שעה',
    name: 'שם',
    enabled: 'מופעל',
    advanced: 'מתקדם',
    icon: 'סמל',
    colour: 'צבע',
    save: 'שמירה',
    cancel: 'ביטול',
    delete_rule: 'מחיקה',
    duplicate: 'שכפול',
    read_only: 'אין לך הרשאה לשנות את הלוח.',
    will_conflict: 'הכלל חופף לכלל אחר. אפשר לשמור בכל זאת — שום דבר לא ייפתר עבורך.',
    defaults_title: 'ברירות מחדל משותפות',
    defaults_help: 'כללים יורשים אותן אלא אם הגדירו משלהם.',
    target: 'יעד',
    data: 'נתונים',
    migration_error: 'לא ניתן להמיר את הכלל הזה מהפורמט הישן והוא לא יופעל:',
    preview_banner: 'תצוגה מקדימה — לא השבת הקרובה. התאריכים אינם מוצגים כי הבלוק הזה אינו מתוכנן.',
    inherits_target_from_defaults: 'נורש מברירת המחדל המשותפת:',
    target_none: 'ללא יעד — הכלל לא יפעל על שום דבר.',
    replay_after_restart: 'הפעלה חוזרת לאחר אתחול',
    replay_within_label: 'רק אם עברו פחות מ־',
    replay_help: 'כברירת מחדל כבוי: לאחר אתחול, מה שכבר עבר לא יופעל שוב.',
    conditions: 'תנאים',
    conditions_help: 'כל התנאים חייבים להתקיים, אחרת הכלל לא ירוץ ויציין זאת.',
    add_condition: 'הוספת תנאי',
    remove_condition: 'הסרה',
    condition_unparseable: 'YAML לא תקין — התנאי הזה לא נשמר.',
    condition_not_a_mapping: 'תנאי חייב להיות מפה, כמו `condition: state`.',
    outcome_called: 'הופעל',
    outcome_would_call: 'היה מופעל [הרצה יבשה]',
    outcome_failed: 'לא רץ — נכשל',
    outcome_blocked: 'לא רץ — נחסם',
    outcome_skipped_stale: 'לא רץ — דולג כמיושן',
    outcome_skipped_no_replay: 'לא רץ — היה אמור לרוץ לאחר אתחול, הפעלה חוזרת כבויה',
    outcome_unknown: 'הסתיים ללא תוצאה מדווחת',
    outcome_no_such_entity: 'אין ישות כזו: ',
    outcome_reached_nothing: 'לא הגיע לאף ישות קיימת',
    run_now_button: 'הרצה עכשיו',
    run_now_simulate: 'סימולציה',
    run_now_real: 'הרצה אמיתית',
    run_now_disabled_dirty: 'שמור/י את השינויים תחילה',
    simulate_title: 'בדיקת הלוח',
    simulate_profile: 'אורך הבלוק',
    simulate_day: 'יום',
    simulate_force_conditions: 'לעקוף תנאים',
    simulate_this_day: 'סימולציה ליום זה',
    simulate_run_for_real: 'הרצה אמיתית ליום זה',
    simulate_run_for_real_confirm: 'פעולה זו תפעיל בפועל את המכשירים שלך, בסדר, עבור',
    clone_day_prefix: 'שכפול יום',
    clone_profile_prefix: 'שכפול פרופיל בן',
    clone_profile_suffix: 'ימים',
    clone_target_profile: 'אורך היעד',
    clone_target_day: 'יום היעד',
    clone_extend: 'הוספה',
    clone_overwrite: 'החלפה',
    clone_target_has_rules: 'ליעד כבר יש כללים:',
    clone_confirm: 'שכפול',
    clone_landed: 'שוכפלו',
    clone_failed: 'לא שוכפלו',
    clone_none: 'ללא',
  },
} as const;

export type StringKey = keyof (typeof STRINGS)['en'];

export function t(language: string | undefined, key: StringKey): string {
  const table = language === 'he' ? STRINGS.he : STRINGS.en;
  return table[key];
}
