/** Mirrors the integration's own en/he translations. */

const STRINGS = {
  en: {
    erev: 'Erev',
    day: 'Day',
    candle_lighting: 'Candle lighting',
    havdalah: 'Havdalah',
    master: 'Shabbat Scheduler',
    dry_run: 'Dry run',
    no_block: 'No upcoming Shabbat could be derived from the Jewish Calendar sensors.',
    not_set_up: 'Shabbat Scheduler is not configured.',
    stale: 'Connection lost — showing the last known state.',
    // Deliberately distinct from `stale`. The server was reachable and
    // refused the call - saying "connection lost" there is a wrong
    // diagnosis that sends someone to check the network.
    command_failed: 'That did not go through. Nothing was changed.',
    no_rules: 'No rules for this block.',
    disabled_rule: 'disabled',
    conflict_prefix: 'Conflict',
    devices: 'Devices',
    temperature: 'Temperature',
    hvac_mode: 'Mode',
    fan_mode: 'Fan',
    intersected: 'Showing only what every selected device supports.',
    unreadable: 'Could not read these devices, so their options are unknown:',
    not_climate: 'These devices take no settings — on and off only.',
    kept_setting: 'kept, but this device does not list it',
    edit_rule: 'Edit rule',
    add_rule: 'Add rule',
    time: 'Time',
    action: 'Action',
    name: 'Name',
    enabled: 'Enabled',
    advanced: 'Advanced',
    icon: 'Icon',
    colour: 'Colour',
    script: 'Script',
    replay: 'Re-apply after a restart',
    save: 'Save',
    cancel: 'Cancel',
    delete_rule: 'Delete',
    duplicate: 'Duplicate',
    read_only: 'You do not have permission to change the schedule.',
    will_conflict: 'This overlaps another rule. You can still save it — nothing is resolved for you.',
    defaults_title: 'Shared defaults',
    defaults_help: 'Rules inherit these unless they set their own.',
  },
  he: {
    erev: 'ערב',
    day: 'יום',
    candle_lighting: 'הדלקת נרות',
    havdalah: 'הבדלה',
    master: 'שעון שבת',
    dry_run: 'הרצה יבשה',
    no_block: 'לא ניתן לגזור שבת קרובה מחיישני לוח השנה העברי.',
    not_set_up: 'שעון שבת אינו מוגדר.',
    stale: 'החיבור אבד — מוצג המצב האחרון הידוע.',
    command_failed: 'הפעולה לא בוצעה. שום דבר לא השתנה.',
    no_rules: 'אין כללים לבלוק הזה.',
    disabled_rule: 'מושבת',
    conflict_prefix: 'התנגשות',
    devices: 'מכשירים',
    temperature: 'טמפרטורה',
    hvac_mode: 'מצב',
    fan_mode: 'מאוורר',
    intersected: 'מוצג רק מה שכל המכשירים שנבחרו תומכים בו.',
    unreadable: 'לא ניתן לקרוא את המכשירים האלה, לכן האפשרויות שלהם אינן ידועות:',
    not_climate: 'המכשירים האלה לא מקבלים הגדרות — הפעלה וכיבוי בלבד.',
    kept_setting: 'נשמר, אך המכשיר לא מציג אותו',
    edit_rule: 'עריכת כלל',
    add_rule: 'הוספת כלל',
    time: 'שעה',
    action: 'פעולה',
    name: 'שם',
    enabled: 'מופעל',
    advanced: 'מתקדם',
    icon: 'סמל',
    colour: 'צבע',
    script: 'סקריפט',
    replay: 'החלה מחדש לאחר הפעלה מחדש',
    save: 'שמירה',
    cancel: 'ביטול',
    delete_rule: 'מחיקה',
    duplicate: 'שכפול',
    read_only: 'אין לך הרשאה לשנות את הלוח.',
    will_conflict: 'הכלל חופף לכלל אחר. אפשר לשמור בכל זאת — שום דבר לא ייפתר עבורך.',
    defaults_title: 'ברירות מחדל משותפות',
    defaults_help: 'כללים יורשים אותן אלא אם הגדירו משלהם.',
  },
} as const;

export type StringKey = keyof (typeof STRINGS)['en'];

export function t(language: string | undefined, key: StringKey): string {
  const table = language === 'he' ? STRINGS.he : STRINGS.en;
  return table[key];
}
